import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateDocs } from "../src/generate.js";
import { createHitchChat } from "../src/hitch.js";
import { extractMarkdownDocument, parseReasonedDocs, slimInventory } from "../src/reason.js";
import { analyze } from "../src/generate.js";

const SAMPLE_JSON = JSON.stringify({
  reasoning: "Harbor Desk is a small Express tide API with a health route.",
  readme: "# Harbor Desk\n\nA tiny Express desk that lists tides.\n",
  map: "# Feature Map — Harbor Desk\n\nProven (verify)\n\n`GET /api/health`\n",
  agent: "# AGENT.md — Harbor Desk\n\nSee docs/FEATURE_MAP.md\n\nDo not claim live tide vendor HTTP.\n",
  skill:
    "---\nname: verify-harbor-desk\ndescription: verify Harbor Desk\n---\n\n# Verify Harbor Desk\n\nDefault path: **no secrets**\n\n[docs](../../../docs/FEATURE_MAP.md)\n",
});

const SAMPLE_MARKERS = `<<<REASONING>>>
Harbor Desk is a small Express tide API with a health route.
<<<README>>>
# Harbor Desk

A tiny Express desk that lists tides.
<<<MAP>>>
# Feature Map — Harbor Desk

Proven (verify)

\`GET /api/health\`
<<<AGENT>>>
# AGENT.md — Harbor Desk

See docs/FEATURE_MAP.md

Do not claim live tide vendor HTTP.
<<<SKILL>>>
---
name: verify-harbor-desk
description: verify Harbor Desk
---

# Verify Harbor Desk

Default path: **no secrets**

[docs](../../../docs/FEATURE_MAP.md)
`;

describe("parseReasonedDocs", () => {
  it("reads fenced JSON and stamps the README marker", () => {
    const parsed = parseReasonedDocs(`\`\`\`json\n${SAMPLE_JSON}\n\`\`\``);
    assert.match(parsed.reasoning, /Harbor Desk/);
    assert.match(parsed.docs.readme ?? "", /fieldguide:readme/);
    assert.match(parsed.docs.skill ?? "", /name: verify-harbor-desk/);
    assert.match(parsed.docs.map ?? "", /Generated by Fieldguide/);
  });

  it("reads delimiter markers used by local models", () => {
    const parsed = parseReasonedDocs(SAMPLE_MARKERS);
    assert.match(parsed.reasoning, /Express tide API/);
    assert.match(parsed.docs.readme ?? "", /fieldguide:readme/);
    assert.match(parsed.docs.skill ?? "", /name: verify-harbor-desk/);
  });

  it("rejects incomplete JSON sets", () => {
    const bad = JSON.stringify({
      reasoning: "x",
      readme: "# R",
      map: "# Feature Map — X",
      agent: "# AGENT",
    });
    assert.throws(() => parseReasonedDocs(bad));
  });
});

describe("ModelHitch reason path", () => {
  it("writes reasoned docs from an injected hitch chat, not templates", async () => {
    const root = await mkdtemp(join(tmpdir(), "fieldguide-hitch-"));
    try {
      await writeFile(
        join(root, "package.json"),
        JSON.stringify({ name: "harbor-desk", description: "tides", scripts: { verify: "npm test" } }),
      );
      const { results, reasoning, lane } = await generateDocs({
        root,
        dryRun: false,
        force: true,
        kinds: ["readme", "map", "agent", "skill"],
        llm: true,
        chat: {
          lane: { provider: "mock", model: "mock-model" },
          complete: async () => SAMPLE_JSON,
        },
      });
      assert.equal(lane?.provider, "mock");
      assert.match(reasoning ?? "", /Express tide API/);
      assert.ok(results.every((item) => item.status === "wrote"));
      const readme = await readFile(join(root, "README.md"), "utf8");
      assert.match(readme, /tiny Express desk that lists tides/);
      const map = await readFile(join(root, "docs/FEATURE_MAP.md"), "utf8");
      assert.match(map, /Feature Map — Harbor Desk/);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("falls back to per-document markdown when the first reply is prose", async () => {
    const root = await mkdtemp(join(tmpdir(), "fieldguide-retry-"));
    try {
      await writeFile(join(root, "package.json"), JSON.stringify({ name: "harbor-desk" }));
      let calls = 0;
      const { results } = await generateDocs({
        root,
        dryRun: false,
        force: true,
        kinds: ["readme"],
        llm: true,
        chat: {
          lane: { provider: "mock", model: "mock-model" },
          complete: async () => {
            calls += 1;
            if (calls === 1) return "Sure — I'll draft a README in a moment.";
            return "# Harbor Desk\n\nA tiny Express desk that lists tides.\n";
          },
        },
      });
      assert.ok(calls >= 2);
      const readme = results.find((item) => item.kind === "readme");
      assert.equal(readme?.reason, "reasoned");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("mock provider echoes without needing a key", async () => {
    const hitch = await createHitchChat({ mock: true });
    const text = await hitch.complete([{ role: "user", content: "Clock in." }]);
    assert.match(text, /Clock in/);
  });
});

describe("extractMarkdownDocument", () => {
  it("strips a Sure preamble", () => {
    const text = extractMarkdownDocument(
      "Sure, here you go.\n\n# Harbor Desk\n\nTides.",
      "readme",
      "harbor-desk",
    );
    assert.match(text ?? "", /^# Harbor Desk/m);
  });

  it("never fails the run when hitch returns unusable JSON", async () => {
    const root = await mkdtemp(join(tmpdir(), "fieldguide-jsonjunk-"));
    try {
      await writeFile(join(root, "package.json"), JSON.stringify({ name: "harbor-desk", description: "tides" }));
      const { results } = await generateDocs({
        root,
        dryRun: false,
        force: true,
        kinds: ["readme", "map"],
        llm: true,
        chat: {
          lane: { provider: "mock", model: "mock-model" },
          complete: async () => "{ this is not json and has no markers",
        },
      });
      assert.equal(results.length, 2);
      assert.ok(results.every((item) => item.status === "wrote"));
      const readme = await readFile(join(root, "README.md"), "utf8");
      assert.match(readme, /Harbor Desk|fieldguide:readme/);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});

describe("slimInventory", () => {
  it("omits the full file list", async () => {
    const root = await mkdtemp(join(tmpdir(), "fieldguide-slim-"));
    try {
      await writeFile(join(root, "package.json"), JSON.stringify({ name: "slim-app", version: "1.0.0" }));
      const model = await analyze(root);
      const slim = slimInventory(model);
      assert.equal("files" in slim, false);
      assert.equal(slim.slug, "slim-app");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});

