import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateDocs } from "../src/generate.js";
import { createHitchChat } from "../src/hitch.js";
import { parseReasonedDocs, slimInventory } from "../src/reason.js";
import { analyze } from "../src/generate.js";

const SAMPLE_JSON = JSON.stringify({
  reasoning: "Harbor Desk is a small Express tide API with a health route.",
  readme: "# Harbor Desk\n\nA tiny Express desk that lists tides.\n",
  map: "# Feature Map — Harbor Desk\n\nProven (verify)\n\n`GET /api/health`\n",
  agent: "# AGENT.md — Harbor Desk\n\nSee docs/FEATURE_MAP.md\n\nDo not claim live tide vendor HTTP.\n",
  skill:
    "---\nname: verify-harbor-desk\ndescription: verify Harbor Desk\n---\n\n# Verify Harbor Desk\n\nDefault path: **no secrets**\n\n[docs](../../../docs/FEATURE_MAP.md)\n",
});

describe("parseReasonedDocs", () => {
  it("reads fenced JSON and stamps the README marker", () => {
    const parsed = parseReasonedDocs(`\`\`\`json\n${SAMPLE_JSON}\n\`\`\``);
    assert.match(parsed.reasoning, /Harbor Desk/);
    assert.match(parsed.docs.readme ?? "", /fieldguide:readme/);
    assert.match(parsed.docs.skill ?? "", /name: verify-harbor-desk/);
    assert.match(parsed.docs.map ?? "", /Generated by Fieldguide/);
  });

  it("rejects missing skill frontmatter", () => {
    const bad = JSON.stringify({
      reasoning: "x",
      readme: "# R",
      map: "# Feature Map — X",
      agent: "# AGENT",
      skill: "# no yaml",
    });
    assert.throws(() => parseReasonedDocs(bad));
  });
});

describe("ModelHitch reason path", () => {
  it("writes reasoned docs from an injected hitch chat, not templates", async () => {
    const root = await mkdtemp(join(tmpdir(), "fieldguide-hitch-"));
    try {
      await writeFile(
        join(root, "package.json"),
        JSON.stringify({ name: "harbor-desk", description: "tides", scripts: { verify: "npm test" } }),
      );
      const { results, reasoning, lane } = await generateDocs({
        root,
        dryRun: false,
        force: true,
        kinds: ["readme", "map", "agent", "skill"],
        llm: true,
        chat: {
          lane: { provider: "mock", model: "mock-model" },
          complete: async () => SAMPLE_JSON,
        },
      });
      assert.equal(lane?.provider, "mock");
      assert.match(reasoning ?? "", /Express tide API/);
      assert.ok(results.every((item) => item.status === "wrote"));
      const readme = await readFile(join(root, "README.md"), "utf8");
      assert.match(readme, /tiny Express desk that lists tides/);
      const map = await readFile(join(root, "docs/FEATURE_MAP.md"), "utf8");
      assert.match(map, /Feature Map — Harbor Desk/);
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("mock provider echoes without needing a key", async () => {
    const hitch = await createHitchChat({ mock: true });
    const text = await hitch.complete([{ role: "user", content: "Clock in." }]);
    assert.match(text, /Clock in/);
  });
});

describe("slimInventory", () => {
  it("omits the full file list", async () => {
    const root = await mkdtemp(join(tmpdir(), "fieldguide-slim-"));
    try {
      await writeFile(join(root, "package.json"), JSON.stringify({ name: "slim-app", version: "1.0.0" }));
      const model = await analyze(root);
      const slim = slimInventory(model);
      assert.equal("files" in slim, false);
      assert.equal(slim.slug, "slim-app");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
