import type { HitchChat } from "./hitch.js";

export type EvidenceGrade =
  | "Proven (verify)"
  | "Code-inspected"
  | "Unverified (env-gated)"
  | "Gap";

export type DocKind = "readme" | "map" | "agent" | "skill";

export type PackageManager = "npm" | "pnpm" | "yarn" | "bun" | "unknown";

export interface FileRecord {
  rel: string;
  size: number;
}

export interface RouteHit {
  method: string;
  path: string;
  file: string;
}

export interface EnvHit {
  key: string;
  files: string[];
  inExample: boolean;
}

export interface Integration {
  id: string;
  label: string;
  evidence: string[];
  envKeys: string[];
  grade: EvidenceGrade;
}

export interface StackLayer {
  id: string;
  label: string;
  evidence: string[];
}

export interface FeatureClaim {
  section: string;
  claim: string;
  grade: EvidenceGrade;
  evidence: string;
}

export interface FeatureSection {
  id: string;
  title: string;
  intro?: string;
  claims: FeatureClaim[];
  mustNotClaim?: string[];
}

export interface NamingRow {
  surface: string;
  value: string;
}

export interface ProjectModel {
  root: string;
  folderName: string;
  slug: string;
  packageName: string | null;
  displayName: string;
  description: string;
  version: string | null;
  license: string | null;
  privatePackage: boolean;
  packageManager: PackageManager;
  github: string | null;
  nodeEngine: string | null;
  binNames: string[];
  scripts: Record<string, string>;
  dependencies: string[];
  devDependencies: string[];
  stack: StackLayer[];
  files: FileRecord[];
  treeTop: string[];
  sourceFiles: string[];
  routes: RouteHit[];
  envHits: EnvHit[];
  integrations: Integration[];
  hasLockfile: boolean;
  lockfileName: string | null;
  hasCi: boolean;
  ciFiles: string[];
  hasTests: boolean;
  testFiles: string[];
  existingDocs: string[];
  naming: NamingRow[];
  sections: FeatureSection[];
  defaultVerify: VerifyPlan;
}

export interface VerifyPlan {
  label: string;
  command: string | null;
  stages: VerifyStage[];
  notes: string[];
}

export interface VerifyStage {
  name: string;
  command: string;
  expectedExit: 0;
  proves: string;
  mapClaims: string;
}

export interface GenerateOptions {
  root: string;
  dryRun: boolean;
  force: boolean;
  kinds: DocKind[];
  /** Default true. False writes inventory templates and does not call ModelHitch. */
  llm?: boolean;
  provider?: string;
  model?: string;
  chat?: HitchChat;
}

export interface WriteResult {
  kind: DocKind;
  rel: string;
  status: "wrote" | "skipped" | "dry-run";
  reason?: string;
  body?: string;
}

export const README_MARKER = "<!-- fieldguide:readme -->";
export const GENERATED_BANNER =
  "<!-- Generated by Fieldguide. Treat this as current-state documentation, not a roadmap. -->";
